language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=6.2
  matrix:
    - TAG=6.2 KIBANA_VER=6.2.4 EXTRA_TAG=6
    - TAG=6.1 KIBANA_VER=6.1.4
    - TAG=6.0 KIBANA_VER=6.0.1
    - TAG=5.6 KIBANA_VER=5.6.9 EXTRA_TAG=5
    - TAG=5.5 KIBANA_VER=5.5.3
    - TAG=5.4 KIBANA_VER=5.4.3

script:
  - travis_retry make
  - make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/release.sh"
