version: "2"

services:
  elasticsearch:
    image: anaxexp/elasticsearch:$ES_VER
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: $IMAGE
    depends_on:
      - elasticsearch
